### ISSUE TITLE
Cannot remap a group of files that depend on each other

### ISSUE THREAD

**Issue by TwilightFlower** [CadixDev/Atlas#3]
So, I have a bunch of Minecraft mods that I need to remap. They might all inherit from eachother in unknown ways (Minecraft mods aren't exactly known for declaring their dependencies well.) I tried using `for(...) atlas.use(path)` followed by `for(...) atlas.run(path, outPath)` but that fails with an exception saying that a ZipFileSystem for that jar file already exists.

**Comment by jamierocks** [comment]
I've been toying with this idea in my head anyway, but (assuming you're reusing the `Atlas`) we could expose the class path the same way Mercury does

```java
try (final Atlas atlas = new Atlas()) {
    atlas.getClassPath().add(path);
    atlas.getClassPath().remove(path);
    // whatever
}
```

On a final note, with regards to adding libraries to the Atlas class path - if your mappings are complete (they include overrides basically), then we have no need to query inheritance data (and thus they don't *need* to be on the class path).

**Comment by TwilightFlower** [comment]
In this case, I believe I do need them all on the class path, as it might have e.g. `Subclass` extends `Superclass` extends `RemappedClass` where `Subclass` and `Superclass` are from two different jars.
